name: Teste de build com GCC

on: [push]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Adicionar o caminho do GCC ao PATH
        run: |
          echo "Adicionando D:\ucrt64\bin ao PATH"
          $env:Path = "D:\ucrt64\bin;$env:Path"
          gcc --version

      - name: Criar pasta build
        run: mkdir build

      - name: Compilar hello.c
        run: |
          $env:Path = "D:\ucrt64\bin;$env:Path"
          gcc src/hello.c -o build/hello.exe

      - name: Verificar se compilou
        run: |
          if (Test-Path build\hello.exe) {
            Write-Host "✅ Compilação OK!"
          } else {
            Write-Host "❌ Falha ao compilar."
            exit 1
          }
