name: CI – Build C no Windows

on: [push]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar CMake e Toolchain ARM
        shell: powershell
        run: |
          choco install cmake --installargs '"ADD_CMAKE_TO_PATH=System"' -y
          choco install gcc-arm-embedded -y
          choco install make -y

      - name: Compilar blink com CMake
        shell: powershell
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DPICO_SDK_PATH=lib/pico-sdk -DPICO_BOARD=pico
          make

      - name: Verificar se gerou blink.uf2
        shell: powershell
        run: |
          if (Test-Path build\blink.uf2) {
            Write-Host "✅ Build finalizada com sucesso!"
          } else {
            Write-Error "❌ Arquivo blink.uf2 não encontrado!"
            exit 1
          }
