name: Teste de build

on: [push]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]  # mesma label que você cadastrou no runner

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Criar pasta build
        run: mkdir build

      - name: Compilar o hello.c
        run: gcc src/hello.c -o build/hello.exe

      - name: Verificar se compilou
        run: |
          if exist build\hello.exe (
            echo ✅ Compilação OK!
          ) else (
            echo ❌ Falha ao compilar.
            exit 1
          )
